spring:
  application:
    name: erp-gateway-open
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - "optional:file:/config/infra.yml"
      - "optional:file:/config/auth.yml"

server:
  port: 9002

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,gateway

logging:
  level:
    com.erp: DEBUG
    org.springframework.cloud.gateway: INFO
